"""PDF export functionality."""

import streamlit as st
from datetime import datetime
import base64
from io import BytesIO
try:
    from weasyprint import HTML, CSS
    WEASYPRINT_AVAILABLE = True
except ImportError:
    WEASYPRINT_AVAILABLE = False


def generate_pdf_html(title: str, content: str) -> str:
    """Generate HTML content for PDF export."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            @page {{
                margin: 2cm;
                @bottom-right {{
                    content: "Page " counter(page) " of " counter(pages);
                    font-size: 9pt;
                    color: #666;
                }}
            }}
            body {{
                font-family: 'Helvetica', 'Arial', sans-serif;
                line-height: 1.6;
                color: #333;
                font-size: 11pt;
            }}
            h1 {{
                color: #29B5E8;
                border-bottom: 3px solid #29B5E8;
                padding-bottom: 10px;
                margin-top: 0;
            }}
            h2 {{
                color: #1a8fc9;
                margin-top: 30px;
                border-bottom: 1px solid #E0E0E0;
                padding-bottom: 5px;
            }}
            h3 {{
                color: #29B5E8;
                margin-top: 20px;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin: 15px 0;
                page-break-inside: avoid;
            }}
            th {{
                background-color: #29B5E8;
                color: white;
                padding: 10px;
                text-align: left;
                font-weight: 600;
            }}
            td {{
                padding: 8px;
                border-bottom: 1px solid #E0E0E0;
            }}
            .disclaimer {{
                background-color: #FFF9E6;
                border: 1px solid #FFD700;
                padding: 15px;
                margin: 20px 0;
                border-radius: 5px;
                font-size: 9pt;
            }}
            .info-box {{
                background-color: #F0F8FF;
                border-left: 4px solid #29B5E8;
                padding: 15px;
                margin: 15px 0;
            }}
            .header {{
                text-align: center;
                margin-bottom: 30px;
            }}
            .footer {{
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid #E0E0E0;
                font-size: 9pt;
                color: #666;
                text-align: center;
            }}
            code {{
                background-color: #F5F5F5;
                padding: 2px 5px;
                border-radius: 3px;
                font-family: 'Courier New', monospace;
                font-size: 10pt;
            }}
            pre {{
                background-color: #F5F5F5;
                padding: 15px;
                border-radius: 5px;
                border-left: 3px solid #29B5E8;
                overflow-x: auto;
                font-size: 9pt;
                page-break-inside: avoid;
            }}
            .metric-card {{
                background: linear-gradient(135deg, #29B5E8 0%, #1a8fc9 100%);
                color: white;
                padding: 20px;
                border-radius: 8px;
                text-align: center;
                margin: 15px 0;
                page-break-inside: avoid;
            }}
            .metric-value {{
                font-size: 32pt;
                font-weight: bold;
                margin: 10px 0;
            }}
            .metric-label {{
                font-size: 10pt;
                text-transform: uppercase;
                letter-spacing: 1px;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>{title}</h1>
            <p><strong>Snowflake Notebooks Migration Guide</strong></p>
            <p style="font-size: 9pt; color: #666;">Generated: {timestamp}</p>
        </div>
        
        {content}
        
        <div class="footer">
            <p>This document was generated by the Snowflake Notebooks Migration Tool.</p>
            <p>For questions or support, contact your Snowflake account team.</p>
        </div>
        
        <div class="disclaimer">
            <strong>Pricing Disclaimer:</strong> Cost estimates are based on placeholder rates 
            and may not reflect your actual Snowflake pricing. Please consult with your 
            Snowflake account team for accurate pricing specific to your contract and region.
        </div>
    </body>
    </html>
    """
    return html


def create_pdf_download_button(
    html_content: str,
    title: str,
    filename: str = "export.pdf",
    button_text: str = "Download PDF"
):
    """Create a download button for PDF export."""
    if not WEASYPRINT_AVAILABLE:
        st.warning("PDF export requires WeasyPrint. Install with: pip install weasyprint")
        return

    full_html = generate_pdf_html(title, html_content)

    try:
        # Generate PDF
        pdf_bytes = HTML(string=full_html).write_pdf()

        # Create download button
        b64_pdf = base64.b64encode(pdf_bytes).decode()
        href = f'<a href="data:application/pdf;base64,{b64_pdf}" download="{filename}" style="text-decoration: none;"><button style="background-color: #29B5E8; color: white; padding: 0.5rem 1rem; border: none; border-radius: 6px; cursor: pointer; font-weight: 500;">{button_text}</button></a>'
        st.markdown(href, unsafe_allow_html=True)

    except Exception as e:
        st.error(f"Error generating PDF: {str(e)}")


def format_table_for_pdf(df) -> str:
    """Convert a pandas DataFrame to HTML table for PDF."""
    return df.to_html(index=False, border=0, classes="pdf-table")


def format_sql_for_pdf(sql: str) -> str:
    """Format SQL code for PDF display."""
    return f"<pre><code>{sql}</code></pre>"
